import { createServer, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";

/**
 * Real MCP server mounted with the official SDK (stateless mode, JSON responses).
 *
 * Used to prove that the probe works against a truly conformant server
 * — tool schemas generated by zod, handshake handled by the SDK — and not
 * only against our hand-rolled fixture.
 */
export interface RealServer {
  url: string;
  /** Switches `echo` to an enriched inputSchema → allows testing real drift. */
  setDrift(on: boolean): void;
  close(): Promise<void>;
}

function buildMcpServer(drift: boolean): McpServer {
  const server = new McpServer({ name: "real-fixture", version: "1.0.0" });
  server.registerTool(
    "echo",
    {
      description: "Echo back the provided text.",
      inputSchema: drift ? { text: z.string(), upper: z.boolean().optional() } : { text: z.string() },
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async (args: any) => ({ content: [{ type: "text" as const, text: String(args.text ?? "") }] }),
  );
  server.registerTool(
    "add",
    { description: "Add two numbers.", inputSchema: { a: z.number(), b: z.number() } },
    async ({ a, b }) => ({ content: [{ type: "text" as const, text: String(a + b) }] }),
  );
  return server;
}

export async function startRealServer(): Promise<RealServer> {
  let drift = false;

  const httpServer: Server = createServer((req, res) => {
    if (req.method !== "POST") return void res.writeHead(405).end();
    void (async () => {
      // Stateless mode: an ephemeral server/transport pair per request.
      const mcp = buildMcpServer(drift);
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: undefined,
        enableJsonResponse: true,
      });
      res.on("close", () => {
        void transport.close();
        void mcp.close();
      });
      await mcp.connect(transport);
      await transport.handleRequest(req, res);
    })();
  });

  await new Promise<void>((resolve) => httpServer.listen(0, "127.0.0.1", resolve));
  const { port } = httpServer.address() as AddressInfo;

  return {
    url: `http://127.0.0.1:${port}/mcp`,
    setDrift: (on) => {
      drift = on;
    },
    close: () =>
      new Promise<void>((resolve, reject) =>
        httpServer.close((err) => (err ? reject(err) : resolve())),
      ),
  };
}
